#!/usr/bin/env python3
"""
replay.py — does the Tiger signal beat the price it's trading against?

    python3 replay.py                    # replay everything in tiger.db
    python3 replay.py --decide-at 8      # signal taken 8 minutes before close

THE QUESTION THIS ASKS
----------------------
Not "would it have made money." That question is unanswerable from recorded
quotes — you don't know what you'd have been filled at, and fill quality is
exactly what turned +$1,244 gross into +$37.74 net.

The question is narrower and far more useful:

    Is the model's probability better calibrated than the market's price?

If it isn't, nothing downstream matters. No sizing rule, no exit discipline,
no execution improvement rescues a forecast that is worse than the quote it is
betting against. If it is, the size of the gap tells you how much edge there
is to work with before fees.

Benchmark is the market's own implied probability. That is a genuinely hard
benchmark — it embeds every other trader's information — and beating it is the
entire claim being tested.

WHY THERE IS NO SIMULATION MODE
-------------------------------
A tempting shortcut is to simulate BTC paths and test the model on them. Do
not. The model ASSUMES a driftless random walk. Simulating a driftless random
walk and then testing it would confirm the assumption by construction and
produce a beautiful, meaningless result. The only informative test is against
prices that were not generated by the model's own premise.

This file therefore refuses to run without recorded data, and refuses to
report a verdict below MIN_WINDOWS. An underpowered backtest is worse than
none, because it produces a number you will remember.
"""

from __future__ import annotations

import argparse
import random
import sqlite3
import statistics
from collections import defaultdict
from pathlib import Path

from fairvalue import fair_prob_above

DB_PATH = Path("tiger.db")
MIN_WINDOWS = 200          # below this, report the sample and stop
BOOTSTRAP_ROUNDS = 2000


def load_windows(conn: sqlite3.Connection, decide_at_min: float):
    """
    One row per settled window: the state at the decision point, plus outcome.

    Outcome uses the LAST recorded index value against floor_strike. That is a
    proxy for settlement, not settlement — the real value is a 60-second BRTI
    average. Rows within the final minute are excluded from the outcome read
    for that reason, and the residual error is a known, bounded limitation
    that belongs in any writeup of these results.
    """
    rows = conn.execute(
        "SELECT ticker, seconds_left, yes_ask, coinbase_spot, floor_strike, "
        "realized_sigma, volume FROM tick "
        "WHERE floor_strike IS NOT NULL AND yes_ask IS NOT NULL "
        "ORDER BY ticker, seconds_left DESC").fetchall()

    by_ticker = defaultdict(list)
    for r in rows:
        by_ticker[r[0]].append(r)

    out = []
    target_s = decide_at_min * 60.0
    for ticker, ticks in by_ticker.items():
        # decision tick: closest to the requested time-to-close
        decision = min(ticks, key=lambda t: abs((t[1] or 0) - target_s))
        # outcome tick: last one recorded OUTSIDE the final settlement minute
        settled = [t for t in ticks if (t[1] or 0) >= 60.0]
        if not settled or decision[1] is None:
            continue
        final = min(settled, key=lambda t: t[1])
        if abs((decision[1] or 0) - target_s) > 90:
            continue                      # no tick near the decision point
        if decision[5] is None or decision[3] is None:
            continue
        out.append(dict(
            ticker=ticker,
            minutes_left=(decision[1] or 0) / 60.0,
            market_p=decision[2],
            spot=decision[3],
            strike=decision[4],
            sigma=decision[5],
            volume=decision[6] or 0,
            outcome=1.0 if (final[3] or 0) > (final[4] or 0) else 0.0,
        ))
    return out


def brier(pairs) -> float:
    return statistics.fmean((p - o) ** 2 for p, o in pairs)


def block_bootstrap(model_pairs, market_pairs, tickers, rounds=BOOTSTRAP_ROUNDS):
    """
    Day-blocked paired bootstrap on the Brier difference.

    Blocked by day because windows within a day share a volatility regime and
    are emphatically not independent. Treating 96 windows from one day as 96
    samples would shrink the confidence interval by a factor of ~10 and
    manufacture significance out of nothing.
    """
    blocks = defaultdict(list)
    for i, t in enumerate(tickers):
        blocks[t[:t.rfind("-")] if "-" in t else t].append(i)
    keys = list(blocks)
    if len(keys) < 3:
        return None

    diffs = []
    for _ in range(rounds):
        idx = []
        for _ in keys:
            idx.extend(blocks[random.choice(keys)])
        m = brier([model_pairs[i] for i in idx])
        k = brier([market_pairs[i] for i in idx])
        diffs.append(k - m)                 # positive => model better
    diffs.sort()
    lo = diffs[int(0.025 * len(diffs))]
    hi = diffs[int(0.975 * len(diffs))]
    return lo, hi


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--decide-at", type=float, default=8.0,
                    help="minutes before close at which the signal is taken")
    ap.add_argument("--db", default=str(DB_PATH))
    args = ap.parse_args()

    path = Path(args.db)
    if not path.exists():
        raise SystemExit(
            f"{path} does not exist.\n"
            "Nothing to replay. Start the recorder first:  python3 tiger.py\n"
            "This harness will not fabricate data to fill the gap.")

    conn = sqlite3.connect(path)
    windows = load_windows(conn, args.decide_at)

    print(f"decision point : {args.decide_at:.0f} minutes before close")
    print(f"windows usable : {len(windows)}\n")

    if len(windows) < MIN_WINDOWS:
        raise SystemExit(
            f"Need {MIN_WINDOWS}+ settled windows for a verdict; have "
            f"{len(windows)}.\n"
            f"At ~96 windows/day on one series that is about "
            f"{MIN_WINDOWS / 96:.1f} days of recording.\n"
            "Reporting a Brier score on this sample would be noise with a "
            "decimal point. Keep recording.")

    model_pairs, market_pairs, tickers = [], [], []
    for w in windows:
        fair = fair_prob_above(w["spot"], w["strike"],
                               w["minutes_left"], w["sigma"])
        model_pairs.append((fair, w["outcome"]))
        market_pairs.append((w["market_p"], w["outcome"]))
        tickers.append(w["ticker"])

    b_model, b_market = brier(model_pairs), brier(market_pairs)
    base = statistics.fmean(o for _, o in market_pairs)
    b_naive = brier([(base, o) for _, o in market_pairs])

    print(f"Brier — always predict base rate : {b_naive:.4f}")
    print(f"Brier — market price             : {b_market:.4f}")
    print(f"Brier — model                    : {b_model:.4f}")
    print(f"\nmodel minus market: {b_model - b_market:+.4f} "
          f"(negative = model better)")

    ci = block_bootstrap(model_pairs, market_pairs, tickers)
    if ci:
        lo, hi = ci
        print(f"95% CI on the improvement: [{lo:+.4f}, {hi:+.4f}]")
        if lo > 0:
            print("\nModel beats the market. Edge is real at this sample size.")
        elif hi < 0:
            print("\nMarket beats the model. Do not trade this signal.")
        else:
            print("\nInterval spans zero — no detectable edge either way. "
                  "More data, or a better volatility estimate.")
    else:
        print("\nToo few distinct days to bootstrap. Keep recording.")


if __name__ == "__main__":
    main()
