import com.agentbridge.kalshihud.Rules;
public class RulesTest {
 static int checks=0;
 static void check(boolean b){checks++;if(!b)throw new AssertionError("check "+checks);}
 public static void main(String[] args){
 check(Rules.quote(.4,.5));check(!Rules.quote(.6,.5));check(!Rules.quote(Double.NaN,.5));check(!Rules.quote(.5,1.1));
 check(Rules.fresh(10001,1,20000));check(!Rules.fresh(10002,1,20000));check(!Rules.fresh(100,101,200));check(!Rules.fresh(200,100,200));
 check(Rules.direction(101,100,.6,.7).contains("YES"));check(Rules.direction(99,100,.3,.4).contains("NO"));check(Rules.direction(99,100,.6,.7).contains("disagree"));
 check(Math.abs(Rules.net(10,.5,.7,.1,.1)-1.8)<1e-9);
 check(Math.abs(Rules.net(10,.5,.3,.1,.1)+2.2)<1e-9);
 try{Rules.net(-1,.5,.7,0,0);throw new AssertionError();}catch(IllegalArgumentException expected){}
 try{Rules.net(1,.5,Double.NaN,0,0);throw new AssertionError();}catch(IllegalArgumentException expected){}
 check(Rules.tickStreak(new double[]{10,9,8,7,6})==-4);
 check(Rules.composite(95100,95000,3,0)>0);
 check(Rules.ghost(95100,95000,40,300,1).contains("LEAN YES"));
 check(!Rules.ghost(95100,95000,40,300,1).contains("BUY"));
 check(Rules.ghost(95000,95000,50,300,-7).contains("BOUNCE"));
 check(Double.isNaN(Rules.ema(new double[]{1,2,3},9)));
 check(Math.abs(Rules.ema(new double[]{10,11,12,13,14,15,16,17,18},3)-17)<1e-6);
 double far=Rules.moveZ(23,77000,.275,480),near=Rules.moveZ(23,77000,.275,40);
 check(far<near);check(far<.4);check(near>3*far);
 check(Rules.moveZ(-23,77000,.275,480)<0);
 check(Double.isNaN(Rules.moveZ(23,77000,.275,0)));
 check(Double.isNaN(Rules.moveZ(Double.NaN,77000,.275,480)));
 check(Rules.scalpVeto(0,.3,.4,.41).contains("no crossing"));
 check(Rules.scalpVeto(2,.01,.4,.41).contains("slow drift"));
 check(Rules.scalpVeto(3,.3,.1,.11).contains("under 30c"));
 check(Rules.scalpVeto(2,.3,.6,.61).isEmpty());
 check(Rules.scalpVeto(0,.01,.75,.76).contains("cheap NO side"));
 check(Rules.scalpVeto(0,.01,.75,.76).contains("no crossing"));
 check(Rules.scalpVeto(0,.01,.75,.76).contains("slow drift"));
 check(Rules.scalpVeto(2,.3,Double.NaN,.61).isEmpty());
 check(Rules.decideOpenCall(40,.6).equals("YES"));
 check(Rules.decideOpenCall(-40,.4).equals("NO"));
 check(Rules.decideOpenCall(3,.515).equals("COINFLIP"));
 check(Rules.firstTrack(1000,61000).equals("FIRST"));
 check(Rules.firstTrack(1000,61001).equals("LATE-FIRST"));
 check(Rules.firstTrack(1000,1000+660000).equals("LATE-FIRST"));
 check(Rules.secondsAfterOpen(1000,61001)==61);
 check(Rules.savedFirstTrack("","Seen in first minute").equals("FIRST"));
 check(Rules.savedFirstTrack("","First seen 11m 0s after open").equals("LATE-FIRST"));
 check(Rules.savedFirstTrack("","").equals("UNKNOWN"));
 check(Rules.observedHeadline("YES","","NO","LATE-FIRST").startsWith("LATE-FIRST LOCK · YES"));
 check(Rules.observedHeadline("COINFLIP","YES","YES","FIRST").startsWith("LATE AFTER COINFLIP · YES"));
 check(Rules.scoreboardLine("FIRST",4,3,2.4).contains("win 75.0% · avg paper ask 60.0¢ · win−ask +15.0 pts"));
 check(Rules.scoreboardLine("FIRST",0,0,0).contains("n=0"));
 check(Rules.firstTier("COINFLIP",Double.NaN,Double.NaN,800).equals("EDGE-COINFLIP"));
 check(Rules.firstTier("YES",5,.53,840).equals("EDGE-COINFLIP"));
 check(Rules.firstTier("YES",40,.58,840).equals("LEAN"));
 check(Rules.firstTier("NO",-100,.37,840).equals("STRONG"));
 check(Rules.firstTier("YES",40,.58,0).isEmpty());
 check(Rules.lateLockWindow(800)&&!Rules.lateLockWindow(50)&&!Rules.lateLockWindow(867)&&!Rules.lateLockWindow(900));
 check(Rules.forecastHeadline("COINFLIP","NO","YES").equals("LATE NO · NOW YES"));
 check(Rules.forecastHeadline("YES",null,"NO").equals("OPEN YES · NOW NO"));
 check(Rules.forecastHeadline("COINFLIP",null,"COINFLIP").contains("WAITING"));
 check(Rules.betLock("YES","NO").equals("YES"));
 check(Rules.betLock("COINFLIP","NO").equals("NO"));
 check(Rules.betLock("COINFLIP","").equals(""));
 check(Rules.betHeadline("COINFLIP","NO","YES").startsWith("LATE LOCK · NO"));
 check(Rules.betHeadline("YES",null,"YES").startsWith("FIRST OBSERVATION LOCK · YES"));
 check(Rules.settleSide(77446,77444).equals("YES"));
 check(Rules.settleSide(77444,77446).equals("NO"));
 check(Rules.lockLabel("FIRST", "NO", .4).contains("NO midpoint 60¢"));
 check(Rules.lockLabel("FIRST", "YES", .4).contains("YES midpoint 40¢"));
 check(!Rules.isSide("COINFLIP")&&Rules.isSide("NO"));
 check(Rules.betHeadline("COINFLIP","NO","YES").contains("not a new call"));
 check(Rules.betHeadline("COINFLIP","NO","YES").contains("against locked call"));
 check(Rules.reuseMarket(100,200,true));check(!Rules.reuseMarket(200,200,true));check(!Rules.reuseMarket(100,200,false));
 check(Rules.observationTiming(880).contains("first minute"));check(Rules.observationTiming(300).contains("10m"));
 check(Rules.gradedStreak("WWLLL").startsWith("3 losses"));
 check(Rules.gradedStreak("LLWW").startsWith("2 wins"));
 check(Rules.gradedStreak("").equals("No graded first calls"));
 check(Rules.decideT0Call(12).equals("YES"));check(Rules.decideT0Call(-3).equals("NO"));check(Rules.decideT0Call(0).equals(""));
 check(Rules.firstObsStrength("YES",.53).contains("53¢"));
 check(Rules.firstObsStrength("NO",.15).contains("85¢"));
 check(Rules.streakHealth("WWLLLL",.71).contains("not a due win"));
 check(!Rules.streakHealth("WWLLLL",.71).contains("47%"));
 check(Rules.flipWatch("YES",.80,-10,120,2).contains("FLIP WATCH"));
 check(Rules.flipWatch("YES",.80,-10,400,2).equals(""));
 check(Rules.liveOdds("YES",.70).contains("70¢"));
 check(!Rules.liveOdds("YES",.70).contains("buy"));
 check(Rules.betFilter("YES",.53).contains("excluded"));
 check(Rules.betFilter("NO",.30).contains("included"));
 check(Rules.skipRich(.92).contains("HIGH PRICE"));
 check(Rules.skipRich(.7).equals(""));
 check(Rules.decideOpenCall(20,.53).equals("YES"));
 check(Rules.tickerOrder("KXBTC15M-26OCT010015-15")>Rules.tickerOrder("KXBTC15M-26SEP302345-45"));
 check(Rules.performanceHealth("WWWWWWWWWWWWWWWWLLLLWWWWWWWWWWLLLLLLLLLL").startsWith("PERFORMANCE DROP"));
 check(Rules.performanceHealth("WL").contains("need 40"));
 System.out.println(checks+" native rule checks passed");
 }
}
